---
title: 'Waterdeep: Dragon Heist'
email: wdh+dnd@cle.ar.it
description: >
  Wir spielen Dungeons and Dragons - Water Deep Dragon Heist.
baseurl: ""  # the subpath of your site, e.g. /blog
url: 'https://wdh.dndaux.de'
site_lang: de

# Build settings
markdown: kramdown
excerpt_separator: '<!-- more -->'
plugins:
  - jekyll-sitemap
  - jekyll-feed

permalink: /:title/
paginate_path: /posts/:num/
paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - glossary_preproc
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  glossary:
    output: false
  quests:
    output: false
